add-panic-variants = "true"
no-context = "true"
pkgname = "galaxy_db"
output = "models"

[mysql]
    dbname = "galaxy"
    host = "45.32.253.249"
    port = 3306
    user = "lance"
    pass = "lancexu1992"
    sslmode = "false"
