// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package galaxy_db

var TableNames = struct {
	SchedulingRecord string
	Task             string
	TaskConfig       string
}{
	SchedulingRecord: "scheduling_record",
	Task:             "task",
	TaskConfig:       "task_config",
}
