// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package galaxy_db

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("SchedulingRecords", testSchedulingRecordsUpsert)

	t.Run("Tasks", testTasksUpsert)

	t.Run("TaskConfigs", testTaskConfigsUpsert)
}
